#!/bin/bash
echo  "
# Generated by dracut initrd
DEVICE=\"eth0\"
ONBOOT=\"yes\"
NM_CONTROLLED=\"no\"
TYPE=\"Ethernet\"
BOOTPROTO=\"static\"
IPADDR=\"192.168.1.$1\"
NETMASK=\"255.255.255.0\"  "  >  /etc/sysconfig/network-scripts/ifcfg-eth0
systemctl restart  network
